### PR TITLE
Some docs and styling

### PR DESCRIPTION
**Pull request by semuelle**
- Added dark mode and fixed CSS
- Added underlined for links in text
- Added announcement bar:

image

- Contribution page
- Added and adapted README contents as nested docs:

image

### CODE REVIEW

**Comment by semuelle** [comment]
@DrW3RK, do I need to merge this into `master` or `gh-pages`? GH says the page is deployed from `gh-pages`, but the branch seems outdated.

**Comment by DrW3RK** [comment]
I setup the CI workflow to deploy the changes made to `master`  to `gh-pages`, although I think grants team does not have permissions to use w3fdeploy account. https://github.com/w3f/grants/blob/master/.github/workflows/publish.yml

**Review by Noc2 — APPROVED** [review]
Happy to approve it. @semuelle Feel free to also ask Mo regarding setting up a deploy account or using existing accounts. At this stage it’s just for testing purposes.

**Comment by semuelle** [comment]
FYI, the deployment went smoothly: https://github.com/w3f/grants/actions/runs/2656320338

**Comment by DrW3RK** [comment]
Awesome! Yeah, I added the OAuth secret key to the repo. That should do I guess!

**Pull request merged**
